/// <reference path="./orm_mirror/orm.d.ts" />

import OrmNS = require('orm')
import SqlQueryNS from 'sqlquery'

declare module "orm" {
    /* Connection About Patch :start */

    /**
     * it should be defined in 'orm' but there is not, so we should fix it
     */
    interface ConnInstanceInOrmConnDriverDB {
        begin: () => any
        commit: () => any
        rollback: () => any
        trans: (func: Function) => any
        execute: Function;
        close: Function;
    }

    interface DbInstanceInOrmConnDriver {
        conn: ConnInstanceInOrmConnDriverDB
    }
    export interface OrigOrmExecQueryOpts {
        [key: string]: any;
    }
    export interface OrigOrmConnDriver {
        // dialog type
        dialect: string;
        propertyToValue: Function;
        valueToProperty: Function;
        insert: Function;
        db: DbInstanceInOrmConnDriver
    }
    /**
     * then we should patch still
     */
    export interface PatchedOrmConnDriver extends OrigOrmConnDriver {
        execQuerySync: (query: SqlQueryNS.Query, opt: OrigOrmExecQueryOpts) => any
    }

    export interface OrmConnectionOpts {
    }
    /* Connection About Patch :end */

    export interface FibORM extends OrmNS.ORM {
        driver: PatchedOrmConnDriver
        begin: () => any
        commit: () => any
        rollback: () => any
        trans: (func: Function) => any

        syncSync(): void;
    }
    // bad annotation but 'db' is used as like 'orm' ever, so we use 'FibOrmDB' to substitute FibORM
    type FibOrmDB = FibORM

    export function connectSync(opts: OrmNS.FibORMIConnectionOptions | string): FibOrmDB;

    export interface FibORMIConnectionOptions extends OrmNS.IConnectionOptions {
        timezone: string;
    }

    interface InstanceAssociationItem {
        name: string;
        field: OrigModelProperty
        // funcname = string;
        getAccessor: string;
        setAccessor: string;
        hasAccessor: string;
        delAccessor: string;
        addAccessor: string;
    }

    interface InstanceOptions extends OrmNS.ModelOptions {
        one_associations: InstanceAssociationItem[]
        many_associations: InstanceAssociationItem[]
        extend_associations: InstanceAssociationItem[]
        association_properties: any 
        fieldToPropertyMap: any
    }

    interface PatchedSyncfiedModelOrInstance {
        /**
         * @important
         * 
         * methods patchSyncfied by 'fib-orm'
         */        
        countSync: Function;
        firstSync: Function;
        lastSync: Function;
        allSync: Function;
        whereSync: Function;
        findSync: Function;
        removeSync: Function;
        runSync: Function;
    }

    interface PatchedSyncfiedInstanceWithDbWriteOperation extends PatchedSyncfiedModelOrInstance {
        saveSync: Function;
        removeSync: Function;
        validateSync: Function;
        modelSync: Function;
    }
    interface PatchedSyncfiedInstanceWithAssociations {
        /**
         * generated by association, but you don't know what it is
         */
        /* getXxx: Function; */
        /* setXxx: Function; */
        /* removeXxx: Function; */

        /* findByXxx: Function; */
        [associationFunc: string]: Function;
    }
    
    // keep compatible to orig one in 'orm'
    interface OrigModelProperty extends OrmNS.Property {
        /**
         * text | number | integer | boolean | date | enum | object | <del>point</del> | binary | serial
         * view details in https://github.com/dresende/node-orm2/wiki/Model-Properties
         */
        type: string
    }
    type OrigAggreteGenerator = (...args: any[]) => OrmNS.IAggregated
    interface OrigHooks extends OrmNS.Hooks {
        afterAutoFetch?: (next?) => void
    }

    export interface FibOrmFixedModel extends OrmNS.Model, OrigHooks, PatchedSyncfiedModelOrInstance {
        new (): FibOrmFixedModelInstance;
        new (...ids: any[]): FibOrmFixedModelInstance;
        
        allProperties: {
            [key: string]: OrigModelProperty
        }

        find(): any /* OrmNS.Model|OrmNS.IChainFind */;

        /**
         * methods used to add associations
         */
        hasOne: (...args: any[]) => any;
        hasMany: (...args: any[]) => any;
        extendsTo: (...args: any[]) => OrmNS.Model;
    }

    export interface FibOrmFindLikeQueryObject {
        [key: string]: any;
    }

    // patch the missing field defined in orm/lib/Instance.js (such as defined by Object.defineProperty)
    export interface FibOrmFixedModelInstance extends OrmNS.Instance {
        /**
         * default property but some has been declared in OrmNS.Instance,
         * so we comment it(e.g. `on: Function`)
         */
        /**(defined) on: Function; */
        /**(defined) save: Function; */
        saved: boolean;
        /**(defined) remove: Function; */
        set: Function;
        markAsDirty: Function;
        dirtyProperties: object;
        isInstance: boolean;
        isPersisted: boolean;
        isShell: boolean;
        /**(defined) validate: Function; */
        __singleton_uid: string | number;
        __opts?: InstanceOptions;
        model: OrmNS.Model;

        [extraProperty: string]: any;
    }

    export interface FibOrmPatchedSyncfiedInstantce extends PatchedSyncfiedInstanceWithDbWriteOperation, PatchedSyncfiedInstanceWithAssociations {
    }

    export interface FibOrmPatchedSyncfiedDueToAggregationInstance {
        /*  function getXxx() */
    }

    // export type FibOrmObjectToPatch = 
    //     FibOrmFixedModel | FibOrmFixedModelInstance 
    //     | FibOrmPatchedSyncfiedInstantce | PatchedSyncfiedInstanceWithDbWriteOperation | PatchedSyncfiedInstanceWithAssociations

    export interface IChainFibORMFind extends PatchedSyncfiedModelOrInstance, SqlQueryNS.SelectQuery {
        only(args: string[]): IChainFibORMFind;
        only(...args: string[]): IChainFibORMFind;
        order(...order: string[]): IChainFibORMFind;
    }
    /* Orm About Patch :end */
}
