/// <reference path="./orm_mirror/orm.d.ts" />

import OrmNS = require('orm')
import SqlQueryNS from 'sqlquery'

declare module "orm" {
    /* Connection About Patch :start */

    /**
     * it should be defined in 'orm' but there is not, so we should fix it
     */
    interface ConnInstanceInOrmConnDriverDB {
    	begin(): void;
        close(): void;
        commit(): void;
        rollback(): void;
        trans(func: Function): boolean
        execute(sql: string, ...args: any[]): any[];
    }

    interface SQLiteConnInstanceInOrmConnDriverDB extends ConnInstanceInOrmConnDriverDB, Class_SQLite {
    }
    interface MySQLConnInstanceInOrmConnDriverDB extends ConnInstanceInOrmConnDriverDB, Class_MySQL {
    }
    interface MSSQLConnInstanceInOrmConnDriverDB extends ConnInstanceInOrmConnDriverDB, Class_MSSQL {
    }

    interface DbInstanceInOrmConnDriver {
        conn: ConnInstanceInOrmConnDriverDB
    }
    export interface OrigOrmExecQueryOpts {
        [key: string]: any;
    }
    export interface OrigOrmConnDriver {
        // dialog type
        dialect: string;
        propertyToValue: Function;
        valueToProperty: Function;
        insert: Function;
        db: DbInstanceInOrmConnDriver
    }
    /**
     * then we should patch still
     */
    export interface PatchedOrmConnDriver extends OrigOrmConnDriver {
        execQuerySync: (query: SqlQueryNS.Query, opt: OrigOrmExecQueryOpts) => any
    }

    export interface OrmConnectionOpts {
    }
    /* Connection About Patch :end */

    export interface FibOrmFixedModelOptions /* extends OrmNS.ModelOptions */ {
        id?: string[];
        autoFetch?: boolean;
        autoFetchLimit?: number;
        cacheFetch?: boolean;
        hooks?: OrmNS.Hooks;
        methods?: { [name: string]: Function };

        [extensibleProperty: string]: any;
    }

    export interface FibORM extends OrmNS.ORM {
        /* all fixed: start */
        models: { [key: string]: FibOrmFixedModel };
        
        use(plugin: string, options?: any): FibORM;
        use(plugin: Plugin, options?: any): FibORM;

        define(name: string, properties: { [key: string]: OrigModelPropertyDefinition }, opts?: FibOrmFixedModelOptions): FibOrmFixedModel;
        ping(callback: (err: Error) => void): FibORM;
        close(callback: (err: Error) => void): FibORM;
        load(file: string, callback: (err: Error) => void): any;
        sync(callback: (err: Error) => void): FibORM;
        drop(callback: (err: Error) => void): FibORM;
        /* all fixed: end */

        /* memeber patch: start */
        driver: PatchedOrmConnDriver
        begin: () => any
        commit: () => any
        rollback: () => any
        trans: (func: Function) => any

        syncSync(): void;
        
        [extraMember: string]: any;
        /* memeber patch: end */
    }
    // bad annotation but 'db' is used as like 'orm' ever, so we use 'FibOrmDB' to substitute FibORM
    type FibOrmDB = FibORM

    export function connectSync(opts: OrmNS.FibORMIConnectionOptions | string): FibOrmDB;

    export interface FibORMIConnectionOptions extends OrmNS.IConnectionOptions {
        timezone: string;
    }

    interface InstanceAssociationItem {
        name: string;
        field: OrigDetailedModelProperty
        // funcname = string;
        getAccessor: string;
        setAccessor: string;
        hasAccessor: string;
        delAccessor: string;
        addAccessor: string;
    }

    interface InstanceOptions extends OrmNS.ModelOptions {
        one_associations: InstanceAssociationItem[]
        many_associations: InstanceAssociationItem[]
        extend_associations: InstanceAssociationItem[]
        association_properties: any 
        fieldToPropertyMap: any
    }

    interface PatchedSyncfiedModelOrInstance {
        /**
         * @important
         * 
         * methods patchSyncfied by 'fib-orm'
         */        
        countSync: Function;
        firstSync: Function;
        lastSync: Function;
        allSync: Function;
        whereSync: Function;
        findSync: Function;
        removeSync: Function;
        runSync: Function;
    }

    interface PatchedSyncfiedInstanceWithDbWriteOperation extends PatchedSyncfiedModelOrInstance {
        saveSync: Function;
        removeSync: Function;
        validateSync: Function;
        modelSync: Function;
    }
    interface PatchedSyncfiedInstanceWithAssociations {
        /**
         * generated by association, but you don't know what it is
         */
        /* getXxx: Function; */
        /* setXxx: Function; */
        /* removeXxx: Function; */

        /* findByXxx: Function; */
        [associationFunc: string]: Function;
    }
    
    // keep compatible to orig one in 'orm'
    interface OrigDetailedModelProperty extends OrmNS.Property {
        /**
         * text | number | integer | boolean | date | enum | object | <del>point</del> | binary | serial
         * view details in https://github.com/dresende/node-orm2/wiki/Model-Properties
         */
        type: string
        unique?: boolean
        defaultValue?: any

        unsigned?: boolean
        size?: number
        values?: any[]

        time?: boolean

        big?: boolean
    } 
    type OrigModelPropertyDefinition = OrigDetailedModelProperty |
        String | Boolean | Number | Date | Object | Buffer | any[]

    type OrigAggreteGenerator = (...args: any[]) => OrmNS.IAggregated
    interface OrigHooks extends OrmNS.Hooks {
        afterAutoFetch?: (next?) => void
    }

    export interface FibOrmFixedModel extends OrmNS.Model, OrigHooks, PatchedSyncfiedModelOrInstance {
        (): FibOrmFixedModel;// FibOrmFixedModelInstance;
        (...ids: any[]): FibOrmFixedModel;// FibOrmFixedModelInstance;

        new (): FibOrmFixedModelInstance;
        new (...ids: any[]): FibOrmFixedModelInstance;
        
        properties: { [property: string]: OrigDetailedModelProperty }
        allProperties: { [key: string]: OrigDetailedModelProperty }

        find(): any /* OrmNS.Model|OrmNS.IChainFind */;

        /**
         * methods used to add associations
         */
        hasOne: (...args: any[]) => any;
        hasMany: (...args: any[]) => any;
        extendsTo: (...args: any[]) => OrmNS.Model;

        extends: { [extendModel: string]: ExtendModelWrapper };

        [extraProperty: string]: any;
    }

    export interface ExtendModelWrapper {
        // 'hasOne', 'hasMany'
        type: string;
        reversed?: boolean;
        model: FibOrmFixedExtendModel;
    }

    export interface FibOrmFixedExtendModel extends FibOrmFixedModel {
        model_name: string;
    }

    export interface FibOrmFindLikeQueryObject {
        [key: string]: any;
    }

    // patch the missing field defined in orm/lib/Instance.js (such as defined by Object.defineProperty)
    export interface FibOrmFixedModelInstance extends OrmNS.Instance {
        /* all fixed: start */
        on(event: string, callback): FibOrmFixedModelInstance;
        save(): Instance;
        save(data: { [property: string]: any; }, callback: (err: Error) => void): FibOrmFixedModelInstance;
        save(data: { [property: string]: any; }, options: any, callback: (err: Error) => void): FibOrmFixedModelInstance;
        saved: boolean;
        remove(callback: (err: Error) => void): FibOrmFixedModelInstance;
        isInstance: boolean;
        isPersisted: boolean;
        isShell: boolean;
        validate(callback: (errors: Error[]) => void);
        /* all fixed: end */
        
        /* missing fix: start */
        set: Function;
        markAsDirty: Function;
        dirtyProperties: object;
        __singleton_uid: string | number;
        __opts?: InstanceOptions;
        model: FibOrmFixedModel;

        /* missing fix: end */

        [extraProperty: string]: any;
    }

    export interface FibOrmPatchedSyncfiedInstantce extends PatchedSyncfiedInstanceWithDbWriteOperation, PatchedSyncfiedInstanceWithAssociations {
    }

    export interface FibOrmPatchedSyncfiedDueToAggregationInstance {
        /*  function getXxx() */
    }

    // export type FibOrmObjectToPatch = 
    //     FibOrmFixedModel | FibOrmFixedModelInstance 
    //     | FibOrmPatchedSyncfiedInstantce | PatchedSyncfiedInstanceWithDbWriteOperation | PatchedSyncfiedInstanceWithAssociations

    export interface IChainFibORMFind extends PatchedSyncfiedModelOrInstance, SqlQueryNS.SelectQuery {
        only(args: string|string[]): IChainFibORMFind;
        only(...args: string[]): IChainFibORMFind;
        order(...order: string[]): IChainFibORMFind;
    }
    /* Orm About Patch :end */
}
