import { FxOrmSqlDDLSync__SQL } from './Typo/SQL';
import { FxDbDriverNS } from "@fxjs/db-driver/typings/Typo";
export declare function CREATE_TABLE(options: FxOrmSqlDDLSync__SQL.TableOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function ALTER_TABLE_COMMENT(db_type: FxDbDriverNS.DriverType, table: string, comment?: string): string;
export declare function DROP_TABLE(options: FxOrmSqlDDLSync__SQL.TableOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function CHECK_TABLE_HAS_COLUMN(options: FxOrmSqlDDLSync__SQL.CheckTableHasColumnOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function ALTER_TABLE_ADD_COLUMN(options: FxOrmSqlDDLSync__SQL.AddColumnOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function ALTER_TABLE_RENAME_COLUMN(opts: FxOrmSqlDDLSync__SQL.AlertColumnRenameOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function ALTER_TABLE_MODIFY_COLUMN(options: FxOrmSqlDDLSync__SQL.AlterColumnOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function ALTER_TABLE_DROP_COLUMN(options: FxOrmSqlDDLSync__SQL.AlterColumnOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function CREATE_INDEX(options: FxOrmSqlDDLSync__SQL.IndexOptions, db_type: FxDbDriverNS.DriverType): string;
export declare function DROP_INDEX(options: FxOrmSqlDDLSync__SQL.IndexOptions, db_type: FxDbDriverNS.DriverType): string;
