import { FxOrmSqlDDLSync__Dialect } from "../Typo/Dialect";
export declare const hasCollectionSync: FxOrmSqlDDLSync__Dialect.Dialect['hasCollectionSync'];
export declare const hasCollection: FxOrmSqlDDLSync__Dialect.Dialect['hasCollection'];
/**
 * @no_test
 */
export declare const addPrimaryKeySync: FxOrmSqlDDLSync__Dialect.Dialect['addPrimaryKeySync'];
export declare const addPrimaryKey: FxOrmSqlDDLSync__Dialect.Dialect['addPrimaryKey'];
export declare const dropPrimaryKeySync: FxOrmSqlDDLSync__Dialect.Dialect['dropPrimaryKeySync'];
export declare const dropPrimaryKey: FxOrmSqlDDLSync__Dialect.Dialect['dropPrimaryKey'];
export declare const addForeignKeySync: FxOrmSqlDDLSync__Dialect.Dialect['addForeignKeySync'];
export declare const addForeignKey: FxOrmSqlDDLSync__Dialect.Dialect['addForeignKey'];
export declare const dropForeignKeySync: FxOrmSqlDDLSync__Dialect.Dialect['dropForeignKeySync'];
export declare const dropForeignKey: FxOrmSqlDDLSync__Dialect.Dialect['dropForeignKey'];
export declare const getCollectionColumnsSync: FxOrmSqlDDLSync__Dialect.Dialect['getCollectionColumnsSync'];
export declare const getCollectionColumns: FxOrmSqlDDLSync__Dialect.Dialect['getCollectionColumns'];
export declare const getCollectionPropertiesSync: FxOrmSqlDDLSync__Dialect.Dialect['getCollectionPropertiesSync'];
export declare const getCollectionProperties: FxOrmSqlDDLSync__Dialect.Dialect['getCollectionProperties'];
export declare const createCollectionSync: FxOrmSqlDDLSync__Dialect.Dialect['createCollectionSync'];
export declare const createCollection: FxOrmSqlDDLSync__Dialect.Dialect['createCollection'];
export declare const dropCollectionSync: FxOrmSqlDDLSync__Dialect.Dialect['dropCollectionSync'];
export declare const dropCollection: FxOrmSqlDDLSync__Dialect.Dialect['dropCollection'];
export declare const hasCollectionColumnsSync: FxOrmSqlDDLSync__Dialect.Dialect['hasCollectionColumnsSync'];
export declare const hasCollectionColumns: FxOrmSqlDDLSync__Dialect.Dialect['hasCollectionColumns'];
export declare const addCollectionColumnSync: FxOrmSqlDDLSync__Dialect.Dialect['addCollectionColumnSync'];
export declare const addCollectionColumn: FxOrmSqlDDLSync__Dialect.Dialect['addCollectionColumn'];
export declare const renameCollectionColumnSync: FxOrmSqlDDLSync__Dialect.Dialect['renameCollectionColumnSync'];
export declare const renameCollectionColumn: FxOrmSqlDDLSync__Dialect.Dialect['renameCollectionColumn'];
export declare const modifyCollectionColumnSync: FxOrmSqlDDLSync__Dialect.Dialect['modifyCollectionColumnSync'];
export declare const modifyCollectionColumn: FxOrmSqlDDLSync__Dialect.Dialect['modifyCollectionColumn'];
export declare const dropCollectionColumnSync: FxOrmSqlDDLSync__Dialect.Dialect['dropCollectionColumnSync'];
export declare const dropCollectionColumn: FxOrmSqlDDLSync__Dialect.Dialect['dropCollectionColumn'];
export declare const getCollectionIndexesSync: FxOrmSqlDDLSync__Dialect.Dialect['getCollectionIndexesSync'];
export declare const getCollectionIndexes: FxOrmSqlDDLSync__Dialect.Dialect['getCollectionIndexes'];
export declare const addIndexSync: FxOrmSqlDDLSync__Dialect.Dialect['addIndexSync'];
export declare const addIndex: FxOrmSqlDDLSync__Dialect.Dialect['addIndex'];
export declare const removeIndexSync: FxOrmSqlDDLSync__Dialect.Dialect['removeIndexSync'];
export declare const removeIndex: FxOrmSqlDDLSync__Dialect.Dialect['removeIndex'];
export declare const processKeys: FxOrmSqlDDLSync__Dialect.Dialect['processKeys'];
export declare const supportsType: FxOrmSqlDDLSync__Dialect.Dialect['supportsType'];
export declare const getType: FxOrmSqlDDLSync__Dialect.Dialect['getType'];
